// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// Findweights
Rcpp::NumericVector Findweights(NumericVector ONv, NumericVector NNv, NumericVector WEv, int nobs, int nnew, int ntree, double thres, NumericVector counti, int normalise);
RcppExport SEXP quantregRanger_Findweights(SEXP ONvSEXP, SEXP NNvSEXP, SEXP WEvSEXP, SEXP nobsSEXP, SEXP nnewSEXP, SEXP ntreeSEXP, SEXP thresSEXP, SEXP countiSEXP, SEXP normaliseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type ONv(ONvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type NNv(NNvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type WEv(WEvSEXP);
    Rcpp::traits::input_parameter< int >::type nobs(nobsSEXP);
    Rcpp::traits::input_parameter< int >::type nnew(nnewSEXP);
    Rcpp::traits::input_parameter< int >::type ntree(ntreeSEXP);
    Rcpp::traits::input_parameter< double >::type thres(thresSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type counti(countiSEXP);
    Rcpp::traits::input_parameter< int >::type normalise(normaliseSEXP);
    __result = Rcpp::wrap(Findweights(ONv, NNv, WEv, nobs, nnew, ntree, thres, counti, normalise));
    return __result;
END_RCPP
}
