# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Findweights <- function(ONv, NNv, WEv, nobs, nnew, ntree, thres, counti, normalise) {
    .Call('quantregRanger_Findweights', PACKAGE = 'quantregRanger', ONv, NNv, WEv, nobs, nnew, ntree, thres, counti, normalise)
}

Findweightsfast <- function(OrdNv, NNv, filterednodes, index, newindex, WEv, nobs, nnew, ntree, thres, l) {
    .Call('quantregRanger_Findweightsfast', PACKAGE = 'quantregRanger', OrdNv, NNv, filterednodes, index, newindex, WEv, nobs, nnew, ntree, thres, l)
}

Findweightsinbag <- function(ONv, inbag, WEv, nobs, nnew, ntree, thres, counti, normalise) {
    .Call('quantregRanger_Findweightsinbag', PACKAGE = 'quantregRanger', ONv, inbag, WEv, nobs, nnew, ntree, thres, counti, normalise)
}

Findweightsinbagfast <- function(ONv, OrdNv, filterednodes, index, newindex, inbag, WEv, nobs, ntree, thres, l) {
    .Call('quantregRanger_Findweightsinbagfast', PACKAGE = 'quantregRanger', ONv, OrdNv, filterednodes, index, newindex, inbag, WEv, nobs, ntree, thres, l)
}

Findweightsinbagfastimp <- function(ONv, ONvp, OrdNv, filterednodes, index, newindex, inbag, WEv, WEvp, npred, nobs, ntree, thres, l, countbreak) {
    .Call('quantregRanger_Findweightsinbagfastimp', PACKAGE = 'quantregRanger', ONv, ONvp, OrdNv, filterednodes, index, newindex, inbag, WEv, WEvp, npred, nobs, ntree, thres, l, countbreak)
}

test <- function(ONv, NNv, ntree) {
    .Call('quantregRanger_test', PACKAGE = 'quantregRanger', ONv, NNv, ntree)
}

