# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Findweights <- function(ONv, NNv, WEv, nobs, nnew, ntree, thres, counti, normalise) {
    .Call('quantregRanger_Findweights', PACKAGE = 'quantregRanger', ONv, NNv, WEv, nobs, nnew, ntree, thres, counti, normalise)
}

